language: java
jdk:
  - openjdk7
  - oraclejdk7  
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'happyToStudy' ]; then cd .. && eval "mv $currentfolder happyToStudy" && cd happyToStudy; fi
  - npm install -g bower grunt-cli grunt
  - bower install && npm install && grunt
